#!/usr/bin/env bun
// Regenerates packages/api/.dev.vars from the root .env so `wrangler dev`
// works with the same values. Run whenever you change .env.

import { writeFile } from 'node:fs/promises';
import { DEV_VARS_PATH, readRootEnv, WORKER_SECRETS } from './parse-env';

const entries = await readRootEnv();

const lines: string[] = [
  '# Auto-generated by scripts/sync-dev-vars.ts from the root .env.',
  '# DO NOT EDIT BY HAND — regenerate with `bun run sync:dev-vars`.',
  '',
];

let missing = 0;
for (const key of WORKER_SECRETS) {
  const val = entries.get(key);
  if (!val) {
    console.warn(`⚠  ${key} is empty in .env — wrangler dev will fail without it`);
    missing++;
    continue;
  }
  lines.push(`${key}=${val}`);
}

await writeFile(DEV_VARS_PATH, lines.join('\n') + '\n');
console.log(`✓ wrote ${DEV_VARS_PATH} (${WORKER_SECRETS.length - missing}/${WORKER_SECRETS.length} values)`);
